version: "3.9"

services:

  app1:
    build: ./app
    container_name: app1

  app2:
    build: ./app
    container_name: app2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

